// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <RcppEigen.h>
#include <Rcpp.h>

using namespace Rcpp;

#ifdef RCPP_USE_GLOBAL_ROSTREAM
Rcpp::Rostream<true>&  Rcpp::Rcout = Rcpp::Rcpp_cout_get();
Rcpp::Rostream<false>& Rcpp::Rcerr = Rcpp::Rcpp_cerr_get();
#endif

// kmeans_interface
Rcpp::IntegerVector kmeans_interface(Rcpp::IntegerVector K, Rcpp::NumericMatrix data_matrix);
RcppExport SEXP _BeckRPackage_kmeans_interface(SEXP KSEXP, SEXP data_matrixSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< Rcpp::IntegerVector >::type K(KSEXP);
    Rcpp::traits::input_parameter< Rcpp::NumericMatrix >::type data_matrix(data_matrixSEXP);
    rcpp_result_gen = Rcpp::wrap(kmeans_interface(K, data_matrix));
    return rcpp_result_gen;
END_RCPP
}
// dynprog_interface
Eigen::MatrixXd dynprog_interface(Rcpp::IntegerVector K, Eigen::VectorXd data_vec);
RcppExport SEXP _BeckRPackage_dynprog_interface(SEXP KSEXP, SEXP data_vecSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< Rcpp::IntegerVector >::type K(KSEXP);
    Rcpp::traits::input_parameter< Eigen::VectorXd >::type data_vec(data_vecSEXP);
    rcpp_result_gen = Rcpp::wrap(dynprog_interface(K, data_vec));
    return rcpp_result_gen;
END_RCPP
}

static const R_CallMethodDef CallEntries[] = {
    {"_BeckRPackage_kmeans_interface", (DL_FUNC) &_BeckRPackage_kmeans_interface, 2},
    {"_BeckRPackage_dynprog_interface", (DL_FUNC) &_BeckRPackage_dynprog_interface, 2},
    {NULL, NULL, 0}
};

RcppExport void R_init_BeckRPackage(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
