# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

kmeans_interface <- function(K, data_matrix) {
    .Call(`_BeckRPackage_kmeans_interface`, K, data_matrix)
}

dynprog_interface <- function(K, data_vec) {
    .Call(`_BeckRPackage_dynprog_interface`, K, data_vec)
}

